# Generated by Django 3.0.8 on 2020-07-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
